# Generated by Django 3.2.24 on 2024-04-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('employee_designation', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('reenter_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('project_description', models.TextField()),
                ('project_startingdate', models.DateTimeField(auto_now_add=True)),
                ('project_endingdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_experience', models.IntegerField()),
                ('employee_project_allcoateddate', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='users.employee')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_name', to='users.project')),
            ],
        ),
        migrations.CreateModel(
            name='TL_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('task_allocated_date', models.DateTimeField(auto_now_add=True)),
                ('task_ending_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('In Progress', 'Assigned'), ('Completed', 'Not Assigned')], max_length=20)),
                ('Tldb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.tldb')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.project')),
            ],
        ),
    ]
