# Generated by Django 3.2.24 on 2024-04-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tl_task',
            name='Tldb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tldb', to='users.tldb'),
        ),
    ]
